spring.application.name=hotel-booking-api
app.cors.allowed-origin-patterns=*

# Keep API reachable from other containers and host via Docker port mapping.
server.address=0.0.0.0
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
